services:
  - type: web
    name: budget-tracker-server
    env: node
    plan: free
    rootDir: server
    buildCommand: "npm ci"
    startCommand: "node app.js"
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      # Fill these in the Render dashboard after first deploy or prefill here:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
